### ISSUE TITLE
fromNow() in expressions don't read `now` from current context

### ISSUE THREAD

**Issue by jonasfj** [taskcluster/json-e#210] opened 2017-12-04 09:33 UTC
Example:
```yml
$let:
  now: '2015-12-04T09:28:41.186Z'
in:
  - $eval: 'fromNow("2 min")'
  - $eval: 'fromNow("2 min", "2015-12-04T09:28:41.186Z")'
```

@imbstack, shouldn't we fix this? instead of making a hack where the fromNow function have access to the initial context we could just call functions such that they have access to the context...

In golang I wrap with `WrapFunction` or `WrapFunctionWithContext` in which case the first argument of the function is the context..

In JS we can call with `context` as the `this` parameter...  In python, maybe we can set a secret attribute on the function to indicate that it wants to be called with context, and make an annotation that sets this secret attribute... We can just set the attribute to a magic object `{}` like we do with `deleteMarker` and rely on reference comparison (that way it's protected and people can only create it through the annotation).

**Comment by imbstack** [comment] 2017-12-04 20:32
Sure, makes sense to fix if that makes more sense :)

**Comment by sonjita** [comment] 2019-10-04 09:26
Hi @owlishDeveloper and @jonasfj. Can I start working on this issue?

**Comment by owlishDeveloper** [comment] 2019-10-04 11:52
jonasfj doesn't work on json-e anymore :)

**Comment by owlishDeveloper** [comment] 2019-10-04 16:59
@sonjita The issue is assigned to you!

**Comment by escapewindow** [comment] 2019-10-16 18:19
This may have been resolved in years past. I know that for Chain of Trust verification, we specify `now` in the context, so our re-generated task datestrings match the previously generated task's.

**Comment by owlishDeveloper** [comment] 2019-10-17 00:32
@sonjita how's it going?

**Comment by oksmelnik** [comment] 2019-10-21 04:39
I'd like to work on this issue (outreachy applicant)

**Comment by richardgreg** [comment] 2019-10-22 06:15
@owlishDeveloper I don't mind taking a shot at this!

**Comment by oksmelnik** [comment] 2019-10-24 06:22
working on it

**Comment by owlishDeveloper** [comment] 2020-01-09 21:14
> This may have been resolved in years past. I know that for Chain of Trust verification, we specify `now` in the context, so our re-generated task datestrings match the previously generated task's.

I just tried it in playground, and indeed it works. I am going to close this as it appears to be fixed.

**Closed by owlishDeveloper** 2020-01-09 21:14 UTC
Labels: good first issue
